# Databricks notebook source
# DBTITLE 1,initial
spark.sql("create schema if not exists session_8_delta")

# COMMAND ----------

# MAGIC %sql
# MAGIC create or replace table session_8_delta.sample_table_1 (
# MAGIC   id bigint generated by default as identity,
# MAGIC   id_2 bigint generated always as identity ,
# MAGIC   id_3 bigint generated always as (id_2 + 1) ,
# MAGIC   first_name string not null,
# MAGIC   last_name string,
# MAGIC   age int,
# MAGIC   is_active boolean,
# MAGIC   create_date date
# MAGIC ) TBLPROPERTIES (
# MAGIC   'delta.constraints.age_30' = 'age > 30'
# MAGIC   ,'delta.enableChangeDataFeed' = 'true'
# MAGIC   );
# MAGIC
# MAGIC alter table session_8_delta.sample_table_1 add constraint age_20 check (age > 20)

# COMMAND ----------

# DBTITLE 1,for testing
# MAGIC %sql
# MAGIC insert into table session_8_delta.sample_table_1 (first_name,last_name,age,is_active) values
# MAGIC ("yo", 'Doe', 30, true),
# MAGIC ('Jane', 'Doe', 21, false),
# MAGIC ('Bob', 'Smith', 21, null),
# MAGIC ('Alice', 'Johnson', 35, true),
# MAGIC ('Charlie', 'Williams',60,true),
# MAGIC ('Charlie', 'Williams',60,true);
# MAGIC
# MAGIC insert into table session_8_delta.sample_table_1 (id,first_name,last_name,age,is_active) values
# MAGIC (17,"yo", 'Doe', 30, true),
# MAGIC (18,'Jane', 'Doe', 21, false),
# MAGIC (19,'Bob', 'Smith', 21, null),
# MAGIC (20,'Alice', 'Johnson', 35, true),
# MAGIC (21,'Charlie', 'Williams',60,true),
# MAGIC (22,'Charlie', 'Williams',60,true);
# MAGIC
# MAGIC delete from session_8_delta.sample_table_1 where id <7
# MAGIC
# MAGIC
# MAGIC insert into table session_8_delta.sample_table_1 (id_2,first_name,last_name,age,is_active) values
# MAGIC (17,"yo", 'Doe', 30, true),
# MAGIC (18,'Jane', 'Doe', 21, false),
# MAGIC (19,'Bob', 'Smith', 21, null),
# MAGIC (20,'Alice', 'Johnson', 35, true),
# MAGIC (21,'Charlie', 'Williams',60,true),
# MAGIC (22,'Charlie', 'Williams',60,true);
# MAGIC
# MAGIC
# MAGIC select * from session_8_delta.sample_table_1

# COMMAND ----------

# DBTITLE 1,using python api
from delta.tables import *
from pyspark.sql.functions import *
(
    DeltaTable.createOrReplace(spark)
    .tableName("session_8_delta.sample_table_1")
    .addColumn("id","bigint",generatedAlwaysAs= IdentityGenerator())
    .addColumn("id_2","bigint",generatedByDefaultAs= IdentityGenerator())
    .addColumn("id_3","bigint",generatedByDefaultAs= IdentityGenerator(5,2))
    .addColumn("first_name","string",nullable=False)
    .addColumn("last_name","string")
    .addColumn("full_name","string",generatedAlwaysAs="concat_ws(' ', first_name, last_name)")
    .addColumn("age","int",)
    .addColumn("is_active","boolean")
    .addColumn("create_date","date")
    .property("delta.constraints.valid_age", "age >= 18")
    .property("delta.enableChangeDataFeed", "true")
    .execute()
)

# COMMAND ----------

# DBTITLE 1,for testing
# MAGIC %sql
# MAGIC insert into table session_8_delta.sample_table_1 (first_name,last_name,age,is_active) values
# MAGIC ("yo", 'Doe', 30, true),
# MAGIC ('Jane', 'Doe', 21, false),
# MAGIC ('Bob', 'Smith', 21, null),
# MAGIC ('Alice', 'Johnson', 35, true),
# MAGIC ('Charlie', 'Williams',60,true),
# MAGIC ('Charlie', 'Williams',60,true);
# MAGIC
# MAGIC insert into table session_8_delta.sample_table_1 (id_2,first_name,last_name,age,is_active) values
# MAGIC (17,"yo", 'Doe', 30, true),
# MAGIC (18,'Jane', 'Doe', 21, false),
# MAGIC (19,'Bob', 'Smith', 21, null),
# MAGIC (20,'Alice', 'Johnson', 35, true),
# MAGIC (21,'Charlie', 'Williams',60,true),
# MAGIC (22,'Charlie', 'Williams',60,true);
# MAGIC
# MAGIC insert into table session_8_delta.sample_table_1 (last_name,age,is_active) values
# MAGIC ('Doe', 30, true),
# MAGIC ('Doe', 21, false),
# MAGIC ('Smith', 21, null),
# MAGIC ('Johnson', 35, true),
# MAGIC ('Williams',60,true),
# MAGIC ('Williams',60,true);

# COMMAND ----------

# DBTITLE 1,using pyton api to delete update truncate
sample_dt = DeltaTable.forName(spark, "session_8_delta.sample_table_1")

#truncate
sample_dt.delete()

#update
sample_dt.update(condition = col("id") == 3 , set = {"first_name":lit("new_first_name")})

#delete
sample_dt.delete(col("id") < 3)

spark.table("session_8_delta.sample_table_1").display()