# Databricks notebook source
from pyspark.sql import Row
from delta.tables import *

spark.sql("CREATE SCHEMA IF NOT EXISTS session_8_delta")

schema_students_raw = "student_id int, first_name string, last_name string, age int"
data_students_raw = [
    Row(student_id=1, first_name="John", last_name="Doe", age=15),
    Row(student_id=2, first_name="Jane", last_name="Smith", age=16),
    Row(student_id=3, first_name="Michael", last_name="Johnson", age=14)
]
master_students_df = spark.createDataFrame(data_students_raw, schema=schema_students_raw)
master_students_df.createOrReplaceTempView("raw_students")

schema_teachers_raw = "teacher_id int, subject string, years_experience int"
data_teachers_raw = [
    Row(teacher_id=101, subject="Mathematics", years_experience=5),
    Row(teacher_id=102, subject="History", years_experience=12)
]
master_teachers_df = spark.createDataFrame(data_teachers_raw, schema=schema_teachers_raw)
master_teachers_df.createOrReplaceTempView("raw_teachers")

# COMMAND ----------

# MAGIC %md
# MAGIC #### Create Basic Student Table via SQL
# MAGIC 1. Use `spark.sql` to create a Delta table named `session_8_delta.students_sql` if it does not exist.
# MAGIC 2. Include `student_id` (INT), `first_name` (STRING), `last_name` (STRING), and `age` (INT) to match the raw data.

# COMMAND ----------



# COMMAND ----------

# MAGIC %md
# MAGIC #### Insert Initial Data via SQL
# MAGIC 1. Insert the data from the `raw_students` temp view into `session_8_delta.students_sql`.
# MAGIC

# COMMAND ----------



# COMMAND ----------

# MAGIC %md
# MAGIC #### Create Basic Teacher Table via Python API
# MAGIC 1. Use the `DeltaTable.createIfNotExists(spark)` API to build `session_8_delta.teachers_py`.
# MAGIC 2. Add `teacher_id` (INT), `subject` (STRING), and `years_experience` (INT).
# MAGIC
# MAGIC

# COMMAND ----------



# COMMAND ----------

# MAGIC %md
# MAGIC #### Add Identity Column via SQL
# MAGIC 1. Use `spark.sql` to create a Delta table named `session_8_delta.classes_sql` if it does not exist.
# MAGIC 2. Include a `class_record_id` column as a `BIGINT GENERATED BY DEFAULT AS IDENTITY`.
# MAGIC 3. Include `class_name` (STRING) and `room_number` (INT).
# MAGIC
# MAGIC

# COMMAND ----------



# COMMAND ----------

# MAGIC %md
# MAGIC #### Add Generated Column via Python API
# MAGIC 1. Use the `DeltaTable.createIfNotExists(spark)` API to build `session_8_delta.student_profiles_py`.
# MAGIC 2. Add `first_name` (STRING) and `last_name` (STRING).
# MAGIC 3. Add `full_name` generated ALWAYS as the concatenation of first and last name separated by a space.
# MAGIC
# MAGIC

# COMMAND ----------



# COMMAND ----------

# MAGIC %md
# MAGIC #### Add Check Constraint via SQL
# MAGIC 1. Alter the `session_8_delta.students_sql` table.
# MAGIC 2. Add a constraint named `valid_student_age` ensuring `age >= 4`.
# MAGIC

# COMMAND ----------



# COMMAND ----------

# MAGIC %md
# MAGIC #### Enable Table Properties for CDF
# MAGIC 1. Alter the `session_8_delta.teachers_py` table.
# MAGIC 2. Set the table property `delta.enableChangeDataFeed` to `true`.
# MAGIC

# COMMAND ----------



# COMMAND ----------

# MAGIC %md
# MAGIC #### Complex Python API Table Creation
# MAGIC 1. Use `DeltaTable.createOrReplace(spark)` to build `session_8_delta.course_catalog_py`.
# MAGIC 2. Add `course_id` (BIGINT, generated ALWAYS as identity starting at 1000, step 10).
# MAGIC 3. Add `course_name` (STRING, not null).
# MAGIC 4. Add `credits` (INT).
# MAGIC 5. Add a constraint `valid_credits` where credits > 0.
# MAGIC

# COMMAND ----------



# COMMAND ----------

# MAGIC %md
# MAGIC #### Python API Updates
# MAGIC 1. Insert the records from `raw_teachers` into `session_8_delta.teachers_py`.
# MAGIC 2. Using the DeltaTable Python API (`DeltaTable.forName`), instantiate `session_8_delta.teachers_py`.
# MAGIC 3. Update the `subject` of teacher_id 101 to 'Advanced Mathematics'.
# MAGIC

# COMMAND ----------



# COMMAND ----------

# MAGIC %md
# MAGIC #### Programmatic Delete and Truncate
# MAGIC 1. Using the same `dt_teachers` DeltaTable object, delete the record where `years_experience` is less than 10.
# MAGIC 2. Instantiate `session_8_delta.students_sql` and truncate the entire table using the `.delete()` method without conditions.
# MAGIC

# COMMAND ----------

